### ISSUE TITLE
Security Improvements

### ISSUE THREAD

**Issue by teriu** [vital-software/vitalizer#45]
## CSP

**Tasks:**
- [ ] Ensure CSP has been tested correctly

**Reference:**
- [ ] https://medium.com/sourceclear/content-security-policy-with-sentry-efb04f336f59
- [ ] https://csp-evaluator.withgoogle.com
