### ISSUE TITLE
Feature: Upgrade to Webpack 4

### ISSUE THREAD

**Issue by teriu** [vital-software/vitalizer#75]
Vitalizer is in need of some love and attention. We haven't done much to update it recently, and there are some new and interesting tools we can add to our kit. Webpack has gone through an upgrade, and the new major version is out (Webpack 4). As part of the upgrade, we should give Vitalizer in general a little clean, and I propose the following:

### Tasks
- [x] Measure before/after [build time and bundle size](https://twitter.com/TheLarkInn/status/964607133495865351)
- [x] Add [speed-measure-webpack-plugin](https://github.com/stephencookdev/speed-measure-webpack-plugin) to each step in Webpack so we can track time taken
- [x] Upgrade to webpack 4
- [x] Clean up config, make use of new `mode` config
- [ ] Migrate webpack-dev-server to new server

### References
- [Announcing SMP: Speeding Up webpack With Timers](https://codeburst.io/announcing-smp-speeding-up-webpack-with-timers-8387d769e5c7)
- [Webpack 4.0 Release: What's New?](https://auth0.com/blog/webpack-4-release-what-is-new/)
